### ISSUE TITLE
A Docker Image would be nice

### ISSUE THREAD

**Issue by duglin** [openservicebrokerapi/osb-checker#31]
I don't know or use node, so when I tried to run this in a Docker node container I got this:
```
(node:1628) [DEP0006] DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
module.js:545
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/nodejs/mocha/bin/_mocha:7:15)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```
and have no clue what's going on.

Would it be possible to get a Docker image built so I can run the tester that way and just point it to my server w/o having to install (or know) node?

**Comment by leonwanghui** [comment]
Yes you can, I can take a look if nobody is assigned : )

**Comment by leonwanghui** [comment]
@duglin I think this issue can be closed now : ）

**Comment by duglin** [comment]
thanks!
